//
// Created by Isaac Kilis on 5/7/2025.
//

#ifndef OBJECTDESTRUCTORCALLEDBEFORECATCHBLOCKEXAMPLE_H
#define OBJECTDESTRUCTORCALLEDBEFORECATCHBLOCKEXAMPLE_H



class ObjectDestructorCalledBeforeCatchBlockExample {

};



#endif //OBJECTDESTRUCTORCALLEDBEFORECATCHBLOCKEXAMPLE_H
